//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Model1.edmx.Model1.tt
{
    using System;

    public partial class SKU
    {
        public long SKUSYSID { get; set; }
        public Nullable<System.DateTime> SKUSYSDATE { get; set; }
        public string SKUFNYR { get; set; }
        public Nullable<long> SKUCODE { get; set; }
        public Nullable<long> SKUVOUCHNO { get; set; }
        public string SKUPRODUCTCODE { get; set; }
        public string SKUARTNO { get; set; }
        public Nullable<long> SKUARTID { get; set; }
        public string SKUCOLN { get; set; }
        public Nullable<int> SKUCOLID { get; set; }
        public string SKUSIZN { get; set; }
        public Nullable<int> SKUSIZID { get; set; }
        public Nullable<decimal> SKUFEDQTY { get; set; }
        public Nullable<bool> SKUGENMODAUTO { get; set; }
        public Nullable<int> SKUCODSCHEM { get; set; }
        public Nullable<decimal> SKUWSP { get; set; }
        public Nullable<decimal> SKUMRP { get; set; }
        public Nullable<decimal> SKUWSPVAL { get; set; }
        public Nullable<decimal> SKUMRPVAL { get; set; }
        public Nullable<bool> SKUMRKFXPRC { get; set; }
        public Nullable<bool> SKUASORDR { get; set; }
        public Nullable<bool> SKUNMAINTSTK { get; set; }
        public Nullable<bool> SKUARTCOLSET { get; set; }
        public Nullable<bool> SKUARTSIZSET { get; set; }
        public Nullable<int> SKUSIZINDX { get; set; }
        public string SKUCHNO { get; set; }
        public string SKUPONO { get; set; }
        public string SKUDANO { get; set; }
        public Nullable<long> SKUPARTYCODE { get; set; }
        public Nullable<decimal> SKUINQTY { get; set; }
        public Nullable<decimal> SKUSLSQTY { get; set; }
        public Nullable<decimal> SKURTNQTY { get; set; }
        public Nullable<decimal> SKUSTKQTY { get; set; }
        public Nullable<bool> SKUINACT { get; set; }
        public string SKUBY { get; set; }
        public Nullable<decimal> SKUDISCPRCN { get; set; }
        public Nullable<decimal> SKUFLATRT { get; set; }
        public Nullable<decimal> SKUPPRICE { get; set; }
        public Nullable<int> SKUSBSECTIONID { get; set; }
        public string SKUPrintTag { get; set; }
        public string UnitCode { get; set; }
        public string Used { get; set; }
    }
}
